from utilities import processName

requiredCountries = [
    "Thailand",
    "South Korea",
    "England",
    "United Kingdom",
    "Italy",
    "France",
    "Singapore",
    "China",
    "USA",
    "United States of America",
    "United States",
    "Netherlands",
    "The Netherlands",
    "Turkey",
    "Japan",
    "United Arab Emirates",
    "UAE",
    "Austria",
    "Malaysia",
    "Taiwan",
    "China",
    "Spain",
    "Saudi Arabia",
    "India"
]

requiredCities = [
    "Bangkok",
    "Seoul",
    "London",
    "Milan",
    "Paris",
    "Rome",
    "Singapore",
    "Shanghai",
    "New York",
    "New York City",
    "Amsterdam",
    "Istanbul",
    "Tokyo",
    "Dubai",
    "Vienna",
    "Kuala Lumpur",
    "Taipei",
    "Hong Kong",
    "Hong Kong SAR",
    "Riyadh",
    "Barcelona",
    "Los Angeles",
    "Mumbai",
    "New Delhi",
    "Pune",
    "Kolkata",
    "Agra",
    "Jaipur",
    "Bengaluru",
    "Bangalore",
    "Calcutta"
]

cityMappingForRequiredCities = {
    "bangkok": "bangkok",
    "seoul": "seoul",
    "london": "london",
    "milan": "milan",
    "paris": "paris",
    "rome": "rome",
    "singapore": "singapore",
    "shanghai": "shanghai",
    "new-york": "new-york",
    "new-york-city": "new-york",
    "amsterdam": "amsterdam",
    "istanbul": "istanbul",
    "tokyo": 'tokyo',
    "dubai": "dubai",
    "vienna": "vienna",
    "kuala-lumpur": "kuala-lumpur",
    "taipei": "taipei",
    "hong-kong": "hong-kong",
    "hong-kong-sar": "hong-kong",
    "riyadh": "riyadh",
    "barcelona": "barcelona",
    "los-angeles": "los-angeles",
    "mumbai": "mumbai",
    "new-delhi": "new-delhi",
    "pune": "pune",
    "kolkata": "kolkata",
    "calcutta": "kolkata",
    "kolkata-calcutta": "kolkata",
    "agra": "agra",
    "bengaluru": "bangalore",
    "bangalore": "bangalore",
    "bengaluru-bangalore": "bangalore",
    "jaipur": "jaipur"
}

processedRequiredCities = set(list(map(processName, requiredCities)))
processedRequiredCountries = set(list(map(processName, requiredCountries)))


